version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.9
    steps:
      - run:
          name: Build Docker image
          command: docker build -t ravindra-kanitkar-virtoustack/docker-react -f Dockerfile.dev .

      # Add any additional setup steps here if required

      # Run tests inside the Docker container
      - run:
          name: Run Tests
          command: |
            docker run -e CI=true ravindra-kanitkar-virtoustack/docker-react npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
